config/routes.rb
IssueTracker::Application.routes.draw do

  
  resources :users

  
  resources :projects do 
    resources :issues
  end
  
  root :to => "home#index"
  
  match 'home(/:action)' => 'home#index'
  

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  
  validate :name_validate, :description_validate
  
  private
  
  def name_validate
    errors.add 'name', 'nome deve ser preenchido' if name.blank? or name.nil?
  end

  def description_validate
    errors.add 'description', 'description deve ser preenchido' if description.blank? or description.nil?
  end
  
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  
  before_filter :usuario_logado?, :only => [:new, :edit, :create, :update, :destroy]
  
  def index
    @issues = Issue.all
    respond_to do |format|
      format.html # index.html.erb 
      format.xml { render :xml => @issues } 
      format.json { render :json => @issues }
    end
  end
  
  def new
    @issue = Issue.new
  end

  def create
    @project = Project.find params[:project_id]
    @issue = Issue.new params[:issue]
    @issue.project = @project
    @issue.user = User.find_by_name(session[:usuario])
    
    if @issue.save
      format.js do
        @issue = Issue.new
        render :partial => 'issues/issues_operations'
      end
      format.html do
        redirect_to({:controller => :projects, :action => :show, :id => @project.id}, {:notice => 'issue was successfully created.'})
      end
    else
      format.js {render :partial => 'issues/issues_operations'}
      format.html {render :template => 'projects/show'}
    end
  end
    
  def show
    @issue = Issue.find(params[:id])
  end
  
  def edit
    @issue = Issue.find(params[:id])
  end
  
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
        if @issue.update_attributes(params[:issue])
          format.html { redirect_to(@issue, :notice => "Issue was successfully updated.") }
          format.xml { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @issue.errors, :status => :unprocessable_entity }  
        end
    end    
  end
  
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy
    @project = Project.find params[:project_id]
    
    respond_to do |format|
      format.html{redirect_to(@project, :notice => "Issue was successfully deleted.")}
      format.xml { head :ok }
    end
  end  
  
  private
  
  def usuario_logado?
    if session[:usuario].nil? or session[:usuario].blank?
       respond_to do |format|
        format.html { redirect_to(issues_url,:notice => 'Usuario sem permissao.') }
        format.xml  { head :ok }
      end
    end
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_issues_operations.html.erb
<h3>Issues:</h3> 
<%= render :partial => 'issues/list', :locals => {:issues => @project.issues} %>

<h2>New Issue</h2>
<%= render :partial => 'issues/new' %>

app/views/issues/_list.html.erb
<p id="notice"><%= notice %></p>
<% unless issues.empty? %> 
	<ul>
		<% issues.each do |issue| %>
		<li>
			<div> 
				<h3><%= issue.name %></h3> 
				<div><small><%= issue.user.name if not issue.user.nil? %></small> </div>				
				<div><small><%= issue.description %></small> </div>
				<%= link_to 'Remove', project_issue_url(@project.id, issue.id), :confirm => 'Are you sure?', :method => :delete %>
			</div>
		</li>
	</ul>
<% end %> 
<% else %>
	<em>None found.</em>
<% end %>

app/views/issues/_new.html.erb
<%= form_for @issue, :url => project_issues_path(@project) do |f| %>
	<p>
		<%= f.label :name %><br/>
		<%= f.text_field :name %>
	</p>
	<p> 
		<%= f.label :description %><br/>
		<%= f.text_area :description, :size => "50x10" %>
	</p>
	<p>
		<%= submit_tag "Create" %> 
	</p>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>
<p id="notice"><%= notice %></p>
<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @issue.name %>
</p>

<p>
  <b>Description:</b>
  <%= @issue.description %>
</p>

<%=link_to 'Edit', edit_issue_path(@issue)%>  |
<%= link_to 'Back', issues_path %>