config/routes.rb
IssueTracker::Application.routes.draw do

  
  resources :users

  
  resources :projects do 
    resources :issues
  end
  
  root :to => "home#index"
  
  match 'home(/:action)' => 'home#index'
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @user = User.new
    if params[:name]
      @projects = Project.where(['name like ?', "%#{params[:name]}"]).order('created_at desc').limit(2)
    else
      @projects = Project.all :order => 'created_at desc', :limit => 2
    end
  end

  def login
    user_login = params[:user]
    user = User.find_by_name(user_login[:name])    
    if user.correct_password?(user_login[:password])
        session[:usuario] = user.name 
        respond_to do |format|
          format.html { redirect_to root_url}
          format.xml  { head :ok }
        end
     else
          respond_to do |format|
            format.html { redirect_to root_url, :notice => "Password errado!"}
            format.xml  { head :ok }
          end
        end
    end
  
  def logout
      session[:usuario] = nil unless session[:usuario].blank?
      
      respond_to do |format|
        format.html { redirect_to root_url}
        format.xml  { head :ok }
      end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Página Inicial</h1>

<%= form_tag({:controller => :home, :action => :index}, :method => :get) do %>
	<%= label_tag(:name, "Name:") %>
	<%= search_field_tag(:name, params[:name]) %>
	<%= submit_tag("Search") %>
<% end %>

<h3>User Login</h3>
<div id="notice"><%=notice%></div>
<%if session[:usuario].nil? or session[:usuario].blank? %>
	<%= form_for @user, :url => {:action => :login} do |u| %>
		<div class="field">
			<%= u.label :name %>
			<%= u.text_field :name %>
		</div>

		<div class="field">
			<%= u.label :password %>
			<%= u.password_field :password %>
		</div>

		<div class="actions">
	    <%= u.submit 'Login'%>
	  </div>
	<% end %>
<%else%>
	Bem vindo <%=session[:usuario]%>!
<%end%>


<h2>Last 2 Projects</h2>
<% unless @projects.blank? %>
<ul>
	<% @projects.each do |project| %>
		<li><%= link_to project.name, project_path(project.id) %></li>		
	<% end %>
</ul>
<% else %> 
	<em>None found.</em>
<% end %>